version: '3.4'
services:
  db:
    image: sinasheikholeslami/mysql-rest-api-with-spring-boot
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: riiidlabs_assessment_database
    ports:
      - "3308:3306"
    networks:
      - sina-network
  rest-api-with-spring-boot:
      image: sinasheikholeslami/rest-api-with-spring-boot
      restart: always
      build: ./assessment
      working_dir: /assessment
      environment:
        SPRING_BOOT_ENVIRONMENT: Production
      volumes:
        - ./assessment:/assessment
        - ~/.m2:/root/.m2
      ports:
        - "8080:8080"
      command: mvn clean spring-boot:run
      links:
        - db
      depends_on:
        - db
      networks:
        - sina-network
networks:
    sina-network:
        driver: bridge